### Dependency and Loading model

In [5]:
import os
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import load_model

# Load the trained model
model = load_model('model_lstm_i5_7_i1_6.h5')  # Replace with the actual path to your trained model

### Aquire input data for inferencing and Normaliztion
- 'input_data_0000.csv' is the file for input
- converting csv file to numpy array as type float
- Preprocess the input_data if necessary (scaling, normalization, etc.)
  - Scaler_X is for normalizing

In [7]:
data_path = './data_sets'

input_file = os.path.join(data_path, f'input_data_0000.csv')
input_data = np.genfromtxt(input_file, delimiter=',', dtype=int)

# Convert the data to NumPy arrays
input_data = np.array(input_data, dtype=float)

scaler_X = 45.0
input_data = input_data/scaler_X
input_data = input_data.reshape(-1, 5, 7)

print(input_data, type(input_data))

[[[0.26666667 0.35555556 0.46666667 0.53333333 0.91111111 0.95555556
   0.33333333]
  [0.31111111 0.73333333 0.75555556 0.77777778 0.82222222 0.88888889
   0.08888889]
  [0.02222222 0.26666667 0.35555556 0.42222222 0.51111111 0.95555556
   0.75555556]
  [0.17777778 0.31111111 0.62222222 0.64444444 0.75555556 0.88888889
   0.26666667]
  [0.13333333 0.15555556 0.33333333 0.48888889 0.57777778 0.88888889
   0.91111111]]] <class 'numpy.ndarray'>


### Use the model to predict the output_data

In [9]:
predicted_output = model.predict(input_data)

# Postprocess the predicted output_data if necessary
# predicted_output = postprocess_output(predicted_output)

# Print the results
print('Input Data:')
print(input_data)

print('Predicted Output(float):')
print(predicted_output)

predicted_output = predicted_output * 45
print('Predicted Output(float*45):')
print(predicted_output)

predicted_output = np.round(predicted_output)
print('Predicted Output(rounded-up):')
print(predicted_output)

1/1 [==============================] - 0s 15ms/step
Input Data:
[[[0.26666667 0.35555556 0.46666667 0.53333333 0.91111111 0.95555556
   0.33333333]
  [0.31111111 0.73333333 0.75555556 0.77777778 0.82222222 0.88888889
   0.08888889]
  [0.02222222 0.26666667 0.35555556 0.42222222 0.51111111 0.95555556
   0.75555556]
  [0.17777778 0.31111111 0.62222222 0.64444444 0.75555556 0.88888889
   0.26666667]
  [0.13333333 0.15555556 0.33333333 0.48888889 0.57777778 0.88888889
   0.91111111]]]
Predicted Output(float):
[[0.2618189  0.41059437 0.5858117  0.709192   0.8216957  0.92097324]]
Predicted Output(float*45):
[[11.78185  18.476748 26.361525 31.91364  36.976307 41.443794]]
Predicted Output(rounded-up):
[[12. 18. 26. 32. 37. 41.]]
