In [1]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras import layers, models

2023-12-22 00:37:19.518906: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-22 00:37:19.705498: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-22 00:37:19.705562: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-22 00:37:19.739604: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-22 00:37:19.812013: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-22 00:37:19.813050: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [6]:
# Load all datasets from './data_sets'
data_path = './data_sets'
input_datasets = []
output_datasets = []

# Assuming your files are named input_data_1.csv, input_data_2.csv, ..., output_data_1.csv, output_data_2.csv, ...
for i in range(1, 501):
    input_file = os.path.join(data_path, f'input_data_{i:04d}.csv')
    output_file = os.path.join(data_path, f'output_data_{i:04d}.csv')

    # Load data using pandas
    # input_data = pd.read_csv(input_file, delimiter=',', dtype=int).values
    # output_data = pd.read_csv(output_file, delimiter=','dtype=int).values
    input_data = np.genfromtxt(input_file, delimiter=',', dtype=int)
    output_data = np.genfromtxt(output_file, delimiter=',', dtype=int)

    input_datasets.append(input_data)
    output_datasets.append(output_data)

[[12 16 21 24 41 43 15]
 [14 33 34 35 37 40  4]
 [ 1 12 16 19 23 43 34]
 [ 8 14 28 29 34 40 12]
 [ 6  7 15 22 26 40 41]
 [10 17 22 30 35 43 44]
 [ 7 18 19 26 33 45 37]
 [ 6 20 23 24 28 30 44]
 [12 19 21 29 40 45  1]
 [ 4 18 31 37 42 43 40]
 [11 21 22 30 39 44 31]
 [13 14 18 21 34 44 16]
 [11 16 25 27 35 36 37]
 [ 4  7 17 18 38 44 36]
 [ 8 12 13 29 33 42  5]
 [ 3  7 14 15 22 38 17]
 [21 26 27 32 34 42 31]
 [ 1  9 16 23 24 38 17]
 [13 16 23 31 36 44 38]
 [ 4  8 18 24 37 45  6]]


In [3]:
# Convert the data to NumPy arrays
X = np.array(input_datasets, dtype=float)
y = np.array(output_datasets, dtype=float)

# Reshape y to be a 2D array
# y = y.reshape(-1, 1)

# Normalize the input data
# scaler_X = StandardScaler()
# X = scaler_X.fit_transform(X)
scaler_X = 45.0
X = X/scaler_X

# Normalize the output data
# scaler_y = StandardScaler()
# y = scaler_y.fit_transform(y)
scaler_y = 45.0
y = y/scaler_y

In [29]:
print(len(X), len(y))

500 500


In [4]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the LSTM model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(20, 7)))
model.add(Dense(6))  # Output layer with six neurons for regression
model.compile(optimizer='adam', loss='mse')  # Mean Squared Error loss for regression

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

# Evaluate the model
loss = model.evaluate(X_test, y_test, verbose=0)
print(f'Mean Squared Error on Test Set: {loss}')

# Make predictions
predictions = model.predict(X_test)

# Print the predictions
print('Predictions:')
print(predictions)

Epoch 1/50
13/13 [==============================] - 1s 16ms/step - loss: 0.3287 - val_loss: 0.2112
Epoch 2/50
13/13 [==============================] - 0s 7ms/step - loss: 0.1578 - val_loss: 0.0911
Epoch 3/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0552 - val_loss: 0.0236
Epoch 4/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0269 - val_loss: 0.0222
Epoch 5/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0243 - val_loss: 0.0218
Epoch 6/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0244 - val_loss: 0.0210
Epoch 7/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0238 - val_loss: 0.0210
Epoch 8/50
13/13 [==============================] - 0s 8ms/step - loss: 0.0236 - val_loss: 0.0210
Epoch 9/50
13/13 [==============================] - 0s 9ms/step - loss: 0.0251 - val_loss: 0.0212
Epoch 10/50
13/13 [==============================] - 0s 7ms/step - loss: 0.0245 - val_loss: 0.0216
Epoch 11/50
13/13 

In [7]:
model.save('model_lstm_i20_7_i1_6.h5')

/home/karl/anaconda3/envs/ailt00/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
